# Generated by Django 4.2.9 on 2026-01-02 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique job ID used for file naming in Google Drive', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Waiting for Colab processing'), ('PROCESSING', 'Processing - Running in Colab'), ('DONE', 'Done - Results available'), ('FAILED', 'Failed - Error occurred')], default='PENDING', help_text='Current processing status', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text="Detailed status message from Colab (e.g., 'Processing frame 45/120')", null=True)),
                ('input_video_path', models.CharField(help_text='Google Drive path to input video', max_length=500)),
                ('output_video_path', models.CharField(blank=True, help_text='Google Drive path to processed video with emotion annotations', max_length=500, null=True)),
                ('output_json_path', models.CharField(blank=True, help_text='Google Drive path to emotion detection results JSON', max_length=500, null=True)),
                ('colab_notebook_url', models.CharField(help_text='Google Colab notebook URL for manual GPU processing', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last status update time')),
            ],
            options={
                'verbose_name': 'Video Job',
                'verbose_name_plural': 'Video Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
