# Generated by Django 4.2.9 on 2026-01-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending - Waiting for Colab processing'), ('PROCESSING', 'Processing - Running in Colab'), ('DONE', 'Done - Results available'), ('FAILED', 'Failed - Error occurred'), ('CANCELLED', 'Cancelled - Job terminated by user')], default='PENDING', help_text='Current processing status', max_length=20),
        ),
    ]
